import os
import time
import logging
from typing import List, Dict, Any
from docx import Document
from openpyxl import Workbook
from openpyxl.styles import Font
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger("aegis.generators")

class GeneratorError(Exception):
    """Base exception for document generation errors."""
    pass

class SafePathViolationError(GeneratorError):
    """Raised when output file path violates safety directory constraints."""
    pass

class BaseDocumentGenerator:
    """Base document generator class enforcing output directory security boundaries."""
    
    def __init__(self, output_base_dir: str = "outputs"):
        self.output_base_dir = os.path.abspath(output_base_dir)

    def _validate_safe_path(self, filename: str, subfolder: str) -> str:
        """Validates filename is safe and generates target directory structure inside outputs/."""
        if not filename or filename.strip() in [".", ".."]:
            raise SafePathViolationError("Invalid or empty output filename.")
            
        # Normalize Windows backslashes for uniform path resolution across OS platforms
        normalized_filename = filename.replace("\\", "/")
        target_dir = os.path.join(self.output_base_dir, subfolder)
        os.makedirs(target_dir, exist_ok=True)
        
        # Resolve target path before testing containment
        target_path = os.path.abspath(os.path.join(target_dir, normalized_filename))
        
        # Security boundaries check: target file must lie strictly inside subfolder
        if not target_path.startswith(target_dir + os.sep) and target_path != target_dir:
            raise SafePathViolationError("Security breach: path traversal outside safe subfolder directory.")
            
        return target_path

class DocxGenerator(BaseDocumentGenerator):
    """Generates structured DOCX reports/notes using python-docx."""
    
    def generate_docx(self, filename: str, title: str, content: List[Dict[str, Any]]) -> str:
        """Compiles structure list contents to formatted DOCX approval notes/reports."""
        target_path = self._validate_safe_path(filename, "documents")
        
        start_time = time.perf_counter()
        logger.info(f"DOCX Generator: Initiating output compiling for '{filename}'")
        
        try:
            doc = Document()
            
            # Add Title
            doc.add_heading(title, level=0)
            
            # Timestamp metadata header
            ts = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
            meta_p = doc.add_paragraph()
            meta_run = meta_p.add_run(f"Generated by AEGIS: {ts}")
            meta_run.italic = True
            meta_run.font.size = 114300  # 9pt in Emus
            
            for item in content:
                itype = item.get("type")
                text = item.get("text", "")
                
                if itype == "heading":
                    level = item.get("level", 1)
                    doc.add_heading(text, level=level)
                elif itype == "paragraph":
                    doc.add_paragraph(text)
                elif itype == "bullet":
                    doc.add_paragraph(text, style='List Bullet')
                elif itype == "numbered":
                    doc.add_paragraph(text, style='List Number')
                elif itype == "table":
                    headers = item.get("headers", [])
                    rows = item.get("rows", [])
                    
                    if not headers:
                        continue
                        
                    table = doc.add_table(rows=1, cols=len(headers))
                    table.style = 'Light Shading Accent 1'
                    
                    hdr_cells = table.rows[0].cells
                    for idx, header_text in enumerate(headers):
                        hdr_cells[idx].text = str(header_text)
                        
                    for row_data in rows:
                        row_cells = table.add_row().cells
                        for idx, cell_value in enumerate(row_data):
                            row_cells[idx].text = str(cell_value)
            
            doc.save(target_path)
            
        except Exception as e:
            logger.error(f"DOCX generation failed: {e}")
            raise GeneratorError(f"Failed to compile DOCX document: {e}")
            
        duration = int((time.perf_counter() - start_time) * 1000)
        logger.info(f"DOCX Generator: Success. Compiled '{filename}' in {duration}ms")
        return target_path

class XlsxGenerator(BaseDocumentGenerator):
    """Generates structured XLSX spreadsheets using openpyxl."""
    
    def generate_xlsx(self, filename: str, sheets: List[Dict[str, Any]]) -> str:
        """Compiles structure worksheet grids into formatted Excel spreadsheets."""
        target_path = self._validate_safe_path(filename, "spreadsheets")
        
        start_time = time.perf_counter()
        logger.info(f"XLSX Generator: Initiating output compiling for '{filename}'")
        
        try:
            wb = Workbook()
            # Remove default active sheet to use custom list sheets
            wb.remove(wb.active)
            
            if not sheets:
                # Compile default empty sheet if input contains none
                sheets = [{"name": "Report", "headers": ["Status"], "rows": [["Empty Table"]]}]
                
            for idx, sheet_data in enumerate(sheets):
                sheet_name = sheet_data.get("name", f"Sheet{idx+1}")
                ws = wb.create_sheet(title=sheet_name)
                
                headers = sheet_data.get("headers", [])
                rows = sheet_data.get("rows", [])
                
                if headers:
                    ws.append(headers)
                    # Format Header Row (make bold)
                    for cell in ws[1]:
                        cell.font = Font(bold=True)
                        
                for row in rows:
                    ws.append(row)
                    
                # Auto-adjust column widths
                for col in ws.columns:
                    max_len = max(len(str(cell.value or '')) for cell in col)
                    col_letter = col[0].column_letter
                    ws.column_dimensions[col_letter].width = max(max_len + 3, 10)
            
            wb.save(target_path)
            
        except Exception as e:
            logger.error(f"XLSX generation failed: {e}")
            raise GeneratorError(f"Failed to compile XLSX document: {e}")
            
        duration = int((time.perf_counter() - start_time) * 1000)
        logger.info(f"XLSX Generator: Success. Compiled '{filename}' in {duration}ms")
        return target_path

class PdfGenerator(BaseDocumentGenerator):
    """Generates professionally typeset PDF documents using reportlab."""
    
    def generate_pdf(self, filename: str, title: str, content: List[Dict[str, Any]]) -> str:
        """Compiles paragraph flowables, page breaks, and layout style lists into PDF deliverables."""
        target_path = self._validate_safe_path(filename, "pdf")
        
        start_time = time.perf_counter()
        logger.info(f"PDF Generator: Initiating output compiling for '{filename}'")
        
        try:
            doc = SimpleDocTemplate(target_path, pagesize=letter)
            styles = getSampleStyleSheet()
            
            # Professional HexColor palette layout definitions
            title_style = ParagraphStyle(
                'AegisPdfTitle',
                parent=styles['Heading1'],
                fontSize=22,
                leading=26,
                textColor=colors.HexColor('#1B365D'),  # Deep Slate Navy
                spaceAfter=15
            )
            
            heading_style = ParagraphStyle(
                'AegisPdfHeading',
                parent=styles['Heading2'],
                fontSize=14,
                leading=18,
                textColor=colors.HexColor('#008080'),  # Teal Accent
                spaceBefore=12,
                spaceAfter=6
            )
            
            body_style = ParagraphStyle(
                'AegisPdfBody',
                parent=styles['Normal'],
                fontSize=10,
                leading=14,
                spaceAfter=8
            )
            
            bullet_style = ParagraphStyle(
                'AegisPdfBullet',
                parent=body_style,
                leftIndent=15,
                bulletIndent=5
            )
            
            story = []
            
            # Document header title
            story.append(Paragraph(title, title_style))
            ts = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
            story.append(Paragraph(f"Generated by AEGIS: {ts}", ParagraphStyle('PdfMeta', parent=body_style, fontSize=8, textColor=colors.grey)))
            story.append(Spacer(1, 12))
            
            for item in content:
                itype = item.get("type")
                text = item.get("text", "")
                
                if itype == "heading":
                    story.append(Paragraph(text, heading_style))
                elif itype == "paragraph":
                    story.append(Paragraph(text, body_style))
                elif itype == "bullet":
                    story.append(Paragraph(f"&bull; {text}", bullet_style))
                elif itype == "page_break":
                    story.append(PageBreak())
                elif itype == "table":
                    headers = item.get("headers", [])
                    rows = item.get("rows", [])
                    
                    if not headers:
                        continue
                        
                    # Create cell paragraph flowables for clean text auto-wrapping
                    table_data = []
                    
                    # Headers row
                    hdr_row = []
                    for h_val in headers:
                        h_style = ParagraphStyle('HdrStyle', parent=body_style, fontName='Helvetica-Bold', textColor=colors.white)
                        hdr_row.append(Paragraph(str(h_val), h_style))
                    table_data.append(hdr_row)
                    
                    # Data rows
                    for r_val in rows:
                        data_row = []
                        for cell_val in r_val:
                            c_style = ParagraphStyle('CellValStyle', parent=body_style)
                            data_row.append(Paragraph(str(cell_val), c_style))
                        table_data.append(data_row)
                    
                    t = Table(table_data)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1B365D')),
                        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                        ('VALIGN', (0,0), (-1,-1), 'TOP'),
                        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                        ('TOPPADDING', (0,0), (-1,-1), 6),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 10))
            
            doc.build(story)
            
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise GeneratorError(f"Failed to compile PDF document: {e}")
            
        duration = int((time.perf_counter() - start_time) * 1000)
        logger.info(f"PDF Generator: Success. Compiled '{filename}' in {duration}ms")
        return target_path
