"use client";
import React from "react";
import { Alert, Button, Card, Col, Empty, Input, Row, Select, Space, Statistic, Table, Tag, Typography, Upload } from "antd";
import { DeleteOutlined, FileAddOutlined, ReloadOutlined, SearchOutlined, UploadOutlined } from "@ant-design/icons";
import type { DocumentInfo } from "../../lib/api/rag";
const { Dragger } = Upload;
interface Props { documents: DocumentInfo[]; loading: boolean; error: string | null; file: File | null; uploading: boolean; uploadSuccess: string | null; uploadError: string | null; search: string; setSearch: (v:string)=>void; status: string; setStatus:(v:string)=>void; type: string; setType:(v:string)=>void; onFile:(f:File)=>void; onUpload:()=>void; onRefresh:()=>void; onReindex:(id:string)=>void; onDelete:(id:string,name:string)=>void; reindexing:string|null; deleting:string|null; }
export default function DocumentsView(p: Props) {
 const types=[...new Set(p.documents.map(d=>(d.filename.split('.').pop()||'').toUpperCase()).filter(Boolean))];
 const rows=p.documents.filter(d=>d.filename.toLowerCase().includes(p.search.toLowerCase())&&(!p.type||(d.filename.split('.').pop()||'').toUpperCase()===p.type)&&(!p.status||d.status?.toLowerCase().includes(p.status)));
 const columns=[{title:'Document',dataIndex:'filename',render:(v:string)=><Typography.Text strong>{v}</Typography.Text>},{title:'Type',render:(_:unknown,d:DocumentInfo)=><Tag>{(d.filename.split('.').pop()||'FILE').toUpperCase()}</Tag>},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={(v||'ready').match(/fail|error/i)?'error':(v||'').match(/process|ingest/i)?'processing':'success'}>{(v||'READY').toUpperCase()}</Tag>},{title:'Chunks',render:(_:unknown,d:DocumentInfo)=>d.chunk_count??d.chunks??'—',responsive:['md'] as ('md')[]},{title:'Uploaded',dataIndex:'uploaded_at',render:(v:number)=>v?new Date(v*1000).toLocaleString():'Not reported',responsive:['lg'] as ('lg')[]},{title:'Actions',render:(_:unknown,d:DocumentInfo)=><Space><Button size="small" icon={<ReloadOutlined/>} loading={p.reindexing===d.id} onClick={()=>p.onReindex(d.id)}>Reindex</Button><Button size="small" danger icon={<DeleteOutlined/>} loading={p.deleting===d.id} onClick={()=>p.onDelete(d.id,d.filename)}>Delete</Button></Space>}];
 return <div className="aegis-view-stack"><section className="aegis-view-heading"><div><Typography.Title level={2}>Documents</Typography.Title><Typography.Paragraph>Ingest and manage organization documents used by the local knowledge system.</Typography.Paragraph></div><Button icon={<ReloadOutlined/>} onClick={p.onRefresh} loading={p.loading}>Refresh</Button></section><Row gutter={[16,16]}><Col xs={24} sm={8}><Card className="aegis-stat-card"><Typography.Text type="secondary">TOTAL DOCUMENTS</Typography.Text><Statistic value={p.documents.length}/></Card></Col><Col xs={24} sm={8}><Card className="aegis-stat-card"><Typography.Text type="secondary">READY / INDEXED</Typography.Text><Statistic value={p.documents.filter(d=>!/(fail|error|process|ingest)/i.test(d.status||'')).length}/></Card></Col><Col xs={24} sm={8}><Card className="aegis-stat-card"><Typography.Text type="secondary">PROCESSING</Typography.Text><Statistic value={p.documents.filter(d=>/(process|ingest)/i.test(d.status||'')).length}/></Card></Col><Col xs={24} lg={9}><Card title="Add document" className="aegis-panel-card"><Dragger multiple={false} showUploadList={false} beforeUpload={(file)=>{p.onFile(file as unknown as File);return false;}}><p className="ant-upload-drag-icon"><FileAddOutlined /></p><p className="ant-upload-text">Drop a document here or select a file</p><p className="ant-upload-hint">The file is processed by the local AEGIS node.</p></Dragger>{p.file&&<div className="mt-3"><Tag color="blue">{p.file.name}</Tag><Button type="primary" size="small" className="ml-2" icon={<UploadOutlined/>} loading={p.uploading} onClick={p.onUpload}>Ingest document</Button></div>}{p.uploadSuccess&&<Alert className="mt-4" type="success" showIcon message={p.uploadSuccess}/>} {p.uploadError&&<Alert className="mt-4" type="error" showIcon message={p.uploadError}/>}</Card></Col><Col xs={24} lg={15}><Card title="Document library" className="aegis-panel-card"><Space wrap className="mb-4"><Input prefix={<SearchOutlined/>} placeholder="Search documents" value={p.search} onChange={e=>p.setSearch(e.target.value)} allowClear/><Select placeholder="Status" allowClear value={p.status||undefined} onChange={v=>p.setStatus(v||'')} options={[{value:'ready',label:'Ready'},{value:'indexed',label:'Indexed'},{value:'processing',label:'Processing'},{value:'failed',label:'Failed'}]}/><Select placeholder="File type" allowClear value={p.type||undefined} onChange={v=>p.setType(v||'')} options={types.map(value=>({value,label:value}))}/></Space>{p.error?<Alert type="error" showIcon message="Document library unavailable" description={p.error}/>:<Table rowKey="id" loading={p.loading} columns={columns} dataSource={rows} scroll={{x:720}} pagination={{pageSize:8}} locale={{emptyText:<Empty description="No documents match the current filters."/>}}/>}</Card></Col></Row></div>;
}
